name = "BplusTools"
uuid = "9c855568-ef52-4907-8d6a-2b3bbb89a4a6"
authors = ["William Manning <manning.w27@gmail.com>"]
version = "0.2.1"

[deps]
BplusApp = "6498524c-785b-4e26-b825-b7be109d6de7"
BplusCore = "1fb136ff-715c-473e-9ae1-0caef0ff09b1"
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LibCImGui = "9be01004-c4f5-478b-abeb-cb32b114cf5e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.9"
BplusApp = "0.2.1"
BplusCore = "0.2.1"
CImGui = "=1.82.0"
DataStructures = "0.18.15"
LibCImGui = "=1.82.2"
MacroTools = "0.5.12"
Setfield = "1.1"
StaticArrays = "1.8"